### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mevdschee/wped#2]
$ sudo apt-get install php-cli php-curl php-xml elinks
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php-cli
E: Unable to locate package php-curl
E: Unable to locate package php-xml

Ubuntu 14.04

**Comment by mevdschee** [comment]
Those packages may have different names in different distributions, try:

```
sudo apt-get install php5-cli php5-curl php5-xml elinks
```

Kind regards, Maurits

**Comment by vitaly-zdanevich** [comment]
yes, the last problem only with `php5-xml` - I found only `php5-xmlrpc` - this is correct module?

**Comment by vitaly-zdanevich** [comment]
Anyway, it works now, thank you for your effort.

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
